install:  # Install dependencies
	npm install

start: install  # Start the frontend dev server
	npm run dev

build:  # Build the frontend for production
	npm run build

lint:  # Lint the frontend code
	npm run lint

test:  # Run frontend tests
	npm run test

.PHONY: start build lint test install 
